name: 📚 Docs CI for tonystoolbox

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    paths:
      - '**.md'
      - '**.json'
      - '**.yml'

jobs:
  lint-markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g markdownlint-cli
      - run: markdownlint "**/*.md"

  validate-json:
    name: Validate JSON Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint JSON
        run: |
          find . -name '*.json' -exec jq . {} \;

  check-links:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --exclude-mail --no-progress "./**/*.md"

  changelog-release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Generate Release from Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Changelog
        run: |
          git fetch --tags
          git cliff --tag $(git describe --tags) > CHANGELOG.md
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
          files: |
            docs/v1/*.md
